openapi: 3.0.3
info:
  title: To-Do List API Documentation
  version: 1.0.0
  description: |-
    This API allows users to interact with the To-Do backend, including operations such as creating, reading, updating, and deleting tasks. Developers can integrate this API into their frontend applications to manage task-related data.
    
    Repository: https://github.com/dhimasteguh/todos-api"

# servers:
#   - url: http://localhost:3030
#     description: Local server

tags:
  - name: activity
    description: tesss

paths:
  /activity-groups:
    get:
      tags: 
        - activity
      summary: Get all activity groups
      description: tes desc
      # operationId: getActivityGroups
      responses:
        '200':
          description: A JSON array of activity groups
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
                    # updatedAt:
                    #   type: string
                    #   format: date-time
    post:
      summary: Create a new activity group
      operationId: createActivityGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        '201':
          description: Activity group created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityGroup'

  /activity-groups/{id}:
    get:
      summary: Get an activity group by ID
      operationId: getActivityGroupById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details of the specified activity group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityGroup'
        '404':
          description: Activity group not found

    patch:
      summary: Update an activity group
      operationId: updateActivityGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Activity group updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityGroup'
        '404':
          description: Activity group not found

    delete:
      summary: Delete an activity group
      operationId: deleteActivityGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Activity group deleted successfully
        '404':
          description: Activity group not found

  /todo-items:
    get:
      summary: Get all todo items
      operationId: getTodoItems
      parameters:
        - name: activity_group_id
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A JSON array of todo items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'

    post:
      summary: Create a new todo item
      operationId: createTodoItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                activity_group_id:
                  type: integer
              required:
                - title
                - activity_group_id
      responses:
        '201':
          description: Todo item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'

  /todo-items/{id}:
    get:
      summary: Get a todo item by ID
      operationId: getTodoItemById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details of the specified todo item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '404':
          description: Todo item not found

    patch:
      summary: Update a todo item
      operationId: updateTodoItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                is_completed:
                  type: boolean
      responses:
        '200':
          description: Todo item updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
        '404':
          description: Todo item not found

    delete:
      summary: Delete a todo item
      operationId: deleteTodoItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Todo item deleted successfully
        '404':
          description: Todo item not found

components:
  schemas:
    ActivityGroup:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    TodoItem:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        activity_group_id:
          type: integer
        is_completed:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
