openapi: 3.0.3
info:
  title: To-Do List API Documentation
  version: 1.0.0
  
  description: |-
    This API allows users to interact with the To-Do backend, including operations such as creating, reading, updating, and deleting tasks. Developers can integrate this API into their frontend applications to manage task-related data.
    
    Repository: https://github.com/dhimasteguh/todos-api

servers:
  - url: http://localhost:3030
    description: Local server
    
tags:
  - name: Activity
    description: Covers activity group management endpoints.
  - name: To-do
    description: Endpoints for managing individual to-do items within activity groups.
    
paths:
  /activity-groups:
    get:
      tags: 
        - Activity
      summary: Retrieve all activity groups
      description: Fetch a list of all activity groups.
      responses:
        '200':
          description: A list of activity groups
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    created_at:
                      type: string
                      format: date-time
    post:
      tags: 
        - Activity
      summary: Create a new activity group
      description: Add a new activity group to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "To-do Today"
      responses:
        '201':
          description: Activity group created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid input data

  /activity-groups/{id}:
    get:
      tags: 
        - Activity
      summary: Retrieve a specific activity group
      description: Fetch details for an activity group by ID.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the activity group
      responses:
        '200':
          description: Activity group details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  created_at:
                    type: string
                    format: date-time
        '404':
          description: Activity group not found
    patch:
      tags: 
        - Activity
      summary: Update an activity group
      description: Modify details of an activity group by ID.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the activity group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Timebloc"
      responses:
        '200':
          description: Activity group updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  created_at:
                    type: string
                    format: date-time
        '404':
          description: Activity group not found
    delete:
      tags: 
        - Activity
      summary: Delete an activity group
      description: Remove a specific activity group by ID.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the activity group
      responses:
        '204':
          description: Activity group deleted successfully
        '404':
          description: Activity group not found

  /todo-items:
    get:
      tags: 
        - To-do
      summary: Retrieve all to-do items
      description: Fetch a list of all to-do items, optionally filtering by activity group ID.
      parameters:
        - in: query
          name: activity_group_id
          schema:
            type: integer
          required: false
          description: ID of the related activity group
      responses:
        '200':
          description: A list of to-do items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    activity_group_id:
                      type: integer
                    completed:
                      type: boolean
                    created_at:
                      type: string
                      format: date-time
    post:
      tags: 
        - To-do
      summary: Create a new to-do item
      description: Add a new to-do item to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Go to Zahira's wedding"
                activity_group_id:
                  type: integer
                  example: 1
      responses:
        '201':
          description: To-do item created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  activity_group_id:
                    type: integer
                  completed:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time
        '400':
          description: Invalid input data

  /todo-items/{id}:
    get:
      tags: 
        - To-do
      summary: Retrieve a specific to-do item
      description: Fetch details for a specific to-do item by ID.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the to-do item
      responses:
        '200':
          description: To-do item details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  activity_group_id:
                    type: integer
                  completed:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time
        '404':
          description: To-do item not found
    patch:
      tags: 
        - To-do
      summary: Update a to-do item
      description: Modify details of a specific to-do item by ID.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the to-do item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Go to wedding"
                completed:
                  type: boolean
                  example: true
      responses:
        '200':
          description: To-do item updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  activity_group_id:
                    type: integer
                  completed:
                    type: boolean
                  created_at:
                    type: string
                    format: date-time
        '404':
          description: To-do item not found
    delete:
      tags: 
        - To-do
      summary: Delete a to-do item
      description: Remove a specific to-do item by ID.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the to-do item
      responses:
        '204':
          description: To-do item deleted successfully
        '404':
          description: To-do item not found